### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by MComScience** [MComScience/git-html5#1]
- [x] Finish my changes
- [x] Push my commits to GitHub
- [ ] Open a pull request

**Comment by MComScience** [comment]
> * [x]  Finish my changes
> * [ ]  Push my commits to GitHub
> * [ ]  Open a pull request
